[package]
name = "hdim-render"
version = "0.1.0"
edition = "2024"

[dependencies]
hdim-core = { path = "../hdim-core" }
image = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
insta = { workspace = true } # Snapshot testing
